package hibernate.entities;
// Generated 19 oct. 2017 14:39:04 by Hibernate Tools 4.3.1



/**
 * VentesCroisees generated by hbm2java
 */
public class VentesCroisees  implements java.io.Serializable {


     private VentesCroiseesId id;
     private int vente;

    public VentesCroisees() {
    }

    public VentesCroisees(VentesCroiseesId id, int vente) {
       this.id = id;
       this.vente = vente;
    }
   
    public VentesCroiseesId getId() {
        return this.id;
    }
    
    public void setId(VentesCroiseesId id) {
        this.id = id;
    }
    public int getVente() {
        return this.vente;
    }
    
    public void setVente(int vente) {
        this.vente = vente;
    }




}


